apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyle-app
  labels:
    app: kyle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyle-app
  template:
    metadata:
      labels:
        app: kyle-app
    spec:
      containers:
        - name: kyle-app
          image: asia-east1-docker.pkg.dev/smiling-stock-425106-c9/devops-repo/example-app-app:latest
          ports:
            - containerPort: 80
